name = "limt-trading-backend"
main = "worker.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "BRIDGE"
class_name = "Bridge"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Bridge"]
